on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:

  test:
    runs-on: "ubuntu-latest"
    steps:
      # Basic setup
      - uses: "actions/checkout@v6"
      - uses: "astral-sh/setup-uv@v6"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.12"

      # Install the dependencies
      - run: "uv sync --frozen"

      # Run all the tests
      - run: "uv run python -m dl4to4ocp.resize"
      - run: "uv run python -m dl4to4ocp.voxels"
      - run: "uv run python -m example.example"
